FROM mariadb:latest

COPY ./docker/mariadb.cnf /etc/mysql/

ENV MYSQL_ROOT_PASSWORD root
ENV MYSQL_DATABASE fuyuko


#RUN apt -y update
#RUN apt -y upgrade

#RUN curl -sL https://deb.nodesource.com/setup_12.x | bash

#RUN apt -y install curl




