
FROM nginx

COPY dist/fuyuko /usr/share/nginx/html
COPY docker/conf /etc/nginx
COPY update-config-json.sh /usr/share/nginx/

RUN apt -y update && \
    apt -y install apt-utils && \
    apt -y install jq && \
    apt -y install moreutils

VOLUME /usr/share/nginx/html
VOLUME /etc/nginx
VOLUME /var/log/nginx
