
FROM node:12

WORKDIR /usr/src/fuyuko

COPY package*.json ./

COPY . .

RUN apt -y update && \
    apt -y install apt-utils && \
    apt -y install jq && \
    apt -y install moreutils && \
    apt -y install vim && \
    npm install && \
    chmod u+x update-config-json.sh && \
    chmod u+x docker-start-cmd.sh && \
    chmod u+x auto-update-config.sh && \
    set -o vi

EXPOSE 8888

ENTRYPOINT ["/bin/bash",  "-c"]

CMD ["./docker-start-cmd.sh"]

