
FROM node:14

ENV DEBIAN_FRONTEND noninteractive

EXPOSE 8888

WORKDIR /usr/src/fuyuko

COPY tsconfig.json ./
COPY ./*.json ./
COPY ./*.sh ./
COPY ./dist ./dist

RUN apt -y update && \
    apt -y install apt-utils && \
    apt -y install vim && \
    apt -y install mariadb-client-10.1 && \
    npm install && \
    chmod u+x ./*.sh && \
    set -o vi

EXPOSE 8888

ENTRYPOINT ["/bin/bash",  "-c"]

CMD ["./docker-start-cmd.sh"]

