version: "3.3"
services:
  mariadb:
    image: mariadb:10
    ports:
      - 3307:3306
    expose:
      - 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
  be:
    build:
      context: ../be
      dockerfile: docker/dockerfile
    depends_on:
      - db
    command: [
      "./docker-wait-for-db.sh", "--", "node src/app.js", "--FFFdb-host=db", "--FFFdb-port=3306"
    ]
    ports:
      - 8888:8888
    expose:
      - 8888
  fe:
    build:
      context: ../fe
      dockerfile: docker/dockerfile
    depends_on:
      - be
    command: [
      "./docker-wait-for-be.sh", "--", "nginx", "-g", "daemon off;"
    ]