import {
    ActivateInvitationEvent,
    AddCategoryEvent,
    AddCustomRuleToViewEvent,
    AddFavouriteItemIdsEvent,
    AddGlobalAvatarEvent,
    AddGlobalImageEvent,
    AddItemEvent,
    AddItemImageEvent,
    AddItemToPricingStructureEvent,
    AddItemToViewCategoryEvent,
    AddOrUpdateGroupEvent,
    AddOrUpdateItemEvent,
    AddOrUpdatePricingStructuresEvent,
    AddOrUpdateRoleEvent,
    AddOrUpdateRuleEvent,
    AddOrUpdateViewsEvent,
    AddRoleToGroupEvent,
    AddUserEvent,
    AddUserNotificationEvent,
    AddUserToGroupEvent,
    ApproveSelfRegistrationEvent,
    BulkEditJobEvent,
    BulkEditPreviewEvent,
    CategorySimpleItemsInCategoryEvent,
    CategorySimpleItemsNotInCategoryEvent,
    ChangeAttributeStatusEvent,
    ChangeCustomRuleStatusEvent,
    ChangeUserStatusEvent,
    CreateInvitationEvent,
    CreateJwtTokenEvent,
    DecodeJwtTokenEvent,
    DeleteCategoryEvent,
    DeleteCustomRulesEvent,
    DeleteExportArtifactByIdEvent,
    DeleteGroupEvent,
    DeleteItemImageEvent,
    DeleteSelfRegistrationEvent,
    DeleteUserEvent,
    DeleteUserFromGroupEvent, DeleteValidationResultEvent,
    DeleteViewEvent,
    EventSubscriptionRegistry,
    ExportAttributeJobEvent,
    ExportAttributePreviewEvent,
    ExportItemJobEvent,
    ExportItemPreviewEvent,
    ExportPriceJobEvent,
    ExportPricePreviewEvent,
    ForgotPasswordEvent,
    GetAllCustomBulkEditsEvent,
    GetAllCustomExportsEvent,
    GetAllCustomImportsEvent,
    GetAllCustomRulesEvent,
    GetAllCustomRulesForViewEvent,
    GetAllExportArtifactsEvent,
    GetAllFavouritedItemsInViewEvent,
    GetAllFavouriteItemIdsInViewEvent,
    GetAllGlobalAvatarsEvent,
    GetAllGroupsEvent,
    GetAllItemsInViewEvent,
    GetAllJobsEvent,
    GetAllPricingStructureItemsWithPriceEvent,
    GetAllPricingStructuresEvent,
    GetAllRolesEvent,
    GetAllSelfRegistrationsEvent,
    GetAllViewsEvent, GetAllViewValidationsEvent,
    GetAttributeInViewByNameEvent,
    GetAttributeInViewEvent,
    GetAttributesInViewEvent,
    GetCustomBulkEditByIdEvent,
    GetCustomExportByIdEvent,
    GetCustomImportByIdEvent,
    GetExportArtifactContentEvent,
    GetGlobalAvatarContentByNameEvent,
    GetGroupByIdEvent,
    GetGroupByNameEvent,
    GetGroupsWithRoleEvent,
    GetInvitationByCodeEvent,
    GetItemByIdEvent,
    GetItemByNameEvent,
    GetItemImageContentEvent,
    GetItemPrimaryImageEvent,
    GetItemsByIdsEvent,
    GetItemWithFilteringEvent,
    GetJobByIdEvent,
    GetJobDetailsByIdEvent,
    GetNoAvatarContentEvent,
    GetPartnerPricingStructuresEvent,
    GetPricedItemsEvent,
    GetPricedItemsWithFilteringEvent,
    GetPricingStructureByIdEvent,
    GetPricingStructureByNameEvent,
    GetPricingStructureGroupAssociationsEvent,
    GetPricingStructureItemEvent,
    GetPricingStructuresByViewEvent,
    GetRoleByNameEvent,
    GetRuleEvent,
    GetRulesEvent,
    GetSettingsEvent,
    GetUserAvatarContentEvent,
    GetUserByIdEvent,
    GetUserByUsernameEvent,
    GetUserDashboardSerializedDataEvent,
    GetUserDashboardWidgetSerializedDataEvent,
    GetUserNotificationsEvent,
    GetUsersByStatusEvent,
    GetUsersInGroupEvent, GetValidationByViewIdAndValidationIdEvent, GetValidationsByViewIdEvent,
    GetViewByIdEvent,
    GetViewByNameEvent,
    GetViewCategoriesEvent,
    GetViewCategoriesWithItemsEvent,
    GetViewCategoryByNameEvent,
    GetViewCategoryItemsEvent,
    GetViewValidationResultEvent,
    HasAllUserRolesEvent,
    HasAnyUserRolesEvent,
    HasNoneUserRolesEvent,
    ImportAttributeJobEvent,
    ImportAttributePreviewEvent,
    ImportItemJobEvent,
    ImportItemPreviewEvent,
    ImportPriceJobEvent,
    ImportPricePreviewEvent,
    IncomingHttpEvent,
    IsValidForgottenPasswordCodeEvent,
    LinkPricingStructureWithGroupIdEvent,
    LoginEvent,
    LogoutEvent,
    MarkItemImageAsPrimaryEvent,
    newEventSubscriptionRegistry,
    RemoveFavouriteItemIdsEvent,
    RemoveItemFromViewCategoryEvent,
    RemoveRoleFromGroup,
    ResetForgottenPasswordEvent,
    SaveAttributesEvent,
    SaveUserAvatarEvent,
    SaveUserDashboardEvent,
    SaveUserDashboardWidgetDataEvent,
    SearchAttributesByViewEvent,
    SearchForFavouriteItemsInViewEvent,
    SearchForGroupByNameEvent,
    SearchForGroupsWithNoSuchRoleEvent,
    SearchForItemsInViewEvent,
    SearchForUserNotInGroupEvent,
    SearchGroupsAssociatedWithPricingStructureEvent,
    SearchGroupsNotAssociatedWithPricingStructureEvent,
    SearchSelfRegistrationByUsernameEvent,
    SearchUserByUsernameAndStatusEvent,
    SelfRegisterEvent,
    SetPricesEvent,
    UnlinkPricingStructureWithGroupIdEvent,
    UpdateAttributesEvent,
    UpdateCategoryEvent,
    UpdateItemEvent,
    UpdateItemsStatusEvent,
    UpdateItemValueEvent,
    UpdatePricingStructureStatusEvent,
    UpdateRuleStatusEvent,
    UpdateUserEvent,
    UpdateUserSettingsEvent,
    ValidationEvent,
    VerifyJwtTokenEvent
} from "../event.service";
import {Router} from "express";
import {Registry} from "../../../registry";


const d: any = {
    subscription: null,
    IncomingHttpEvent: (evt: IncomingHttpEvent) => {},
    BulkEditPreviewEvent: (evt: BulkEditPreviewEvent) => {},
    BulkEditJobEvent: (evt: BulkEditJobEvent) => {},
    ExportAttributePreviewEvent: (evt: ExportAttributePreviewEvent) => {},
    ExportItemPreviewEvent: (evt: ExportItemPreviewEvent) => {},
    ExportPricePreviewEvent: (evt: ExportPricePreviewEvent) => {},
    ExportAttributeJobEvent: (evt: ExportAttributeJobEvent) => {},
    ExportItemJobEvent: (evt: ExportItemJobEvent) => {},
    ExportPriceJobEvent: (evt: ExportPriceJobEvent) => {},
    ImportAttributePreviewEvent: (evt: ImportAttributePreviewEvent) => {},
    ImportItemPreviewEvent: (evt: ImportItemPreviewEvent) => {},
    ImportPricePreviewEvent: (evt: ImportPricePreviewEvent) => {},
    ImportAttributeJobEvent: (evt: ImportAttributeJobEvent) => {},
    ImportItemJobEvent: (evt: ImportItemJobEvent) => {},
    ImportPriceJobEvent: (evt: ImportPriceJobEvent) => {},
    ValidationEvent: (evt: ValidationEvent) => {},
    UpdateAttributesEvent: (evt: UpdateAttributesEvent) => {},
    ChangeAttributeStatusEvent: (evt: ChangeAttributeStatusEvent) => {},
    GetAttributeInViewByNameEvent: (evt: GetAttributeInViewByNameEvent) => {},
    GetAttributeInViewEvent: (evt: GetAttributeInViewEvent) => {},
    GetAttributesInViewEvent: (evt: GetAttributesInViewEvent) => {},
    SaveAttributesEvent: (evt: SaveAttributesEvent) => {},
    SearchAttributesByViewEvent: (evt: SearchAttributesByViewEvent) => {},
    IsValidForgottenPasswordCodeEvent: (evt: IsValidForgottenPasswordCodeEvent) => {},
    ResetForgottenPasswordEvent: (evt: ResetForgottenPasswordEvent) => {},
    ForgotPasswordEvent: (evt: ForgotPasswordEvent) => {},
    LoginEvent: (evt: LoginEvent) => {},
    LogoutEvent: (evt: LogoutEvent) => {},
    AddGlobalAvatarEvent: (evt: AddGlobalAvatarEvent) => {},
    AddGlobalImageEvent: (evt: AddGlobalImageEvent) => {},
    SaveUserAvatarEvent: (evt: SaveUserAvatarEvent) => {},
    GetGlobalAvatarContentByNameEvent: (evt: GetGlobalAvatarContentByNameEvent) => {},
    GetAllGlobalAvatarsEvent: (evt: GetAllGlobalAvatarsEvent) => {},
    CategorySimpleItemsInCategoryEvent: (evt: CategorySimpleItemsNotInCategoryEvent) => {},
    CategorySimpleItemsNotInCategoryEvent: (evt: CategorySimpleItemsNotInCategoryEvent) => {},
    UpdateCategoryEvent: (evt: UpdateCategoryEvent) => {},
    AddCategoryEvent: (evt: AddCategoryEvent) => {},
    DeleteCategoryEvent: (evt: DeleteCategoryEvent) => {},
    GetViewCategoryByNameEvent: (evt: GetViewCategoryByNameEvent) => {},
    GetViewCategoriesEvent: (evt: GetViewCategoriesEvent) => {},
    GetViewCategoriesWithItemsEvent: (evt: GetViewCategoriesWithItemsEvent) => {},
    GetViewCategoryItemsEvent: (evt: GetViewCategoryItemsEvent) => {},
    AddItemToViewCategoryEvent: (evt: AddItemToViewCategoryEvent) => {},
    RemoveItemFromViewCategoryEvent: (evt: RemoveItemFromViewCategoryEvent) => {},
    GetCustomBulkEditByIdEvent: (evt: GetCustomBulkEditByIdEvent) => {},
    GetAllCustomBulkEditsEvent: (evt: GetAllCustomBulkEditsEvent) => {},
    GetCustomExportByIdEvent: (evt: GetCustomExportByIdEvent) => {},
    GetAllCustomExportsEvent: (evt: GetAllCustomExportsEvent) => {},
    GetCustomImportByIdEvent: (evt: GetCustomImportByIdEvent) => {},
    GetAllCustomImportsEvent: (evt: GetAllCustomImportsEvent) => {},
    ChangeCustomRuleStatusEvent: (evt: ChangeCustomRuleStatusEvent) => {},
    AddCustomRuleToViewEvent: (evt: AddCustomRuleToViewEvent) => {},
    GetAllCustomRulesEvent: (evt: GetAllCustomRulesEvent) => {},
    GetAllCustomRulesForViewEvent: (evt: GetAllCustomRulesForViewEvent) => {},
    DeleteCustomRulesEvent: (evt: DeleteCustomRulesEvent) => {},
    SaveUserDashboardWidgetDataEvent: (evt: SaveUserDashboardEvent) => {},
    SaveUserDashboardEvent: (evt: SaveUserDashboardEvent) => {},
    GetUserDashboardWidgetSerializedDataEvent: (evt: GetUserDashboardWidgetSerializedDataEvent) => {},
    GetUserDashboardSerializedDataEvent: (evt: GetUserDashboardSerializedDataEvent) => {},
    GetExportArtifactContentEvent: (evt: GetExportArtifactContentEvent) => {},
    DeleteExportArtifactByIdEvent: (evt: DeleteExportArtifactByIdEvent) => {},
    GetAllExportArtifactsEvent: (evt: GetAllExportArtifactsEvent) => {},
    CreateInvitationEvent: (evt: CreateInvitationEvent) => {},
    ActivateInvitationEvent: (evt: ActivateInvitationEvent) => {},
    GetInvitationByCodeEvent: (evt: GetInvitationByCodeEvent) => {},
    DeleteGroupEvent: (evt: DeleteGroupEvent) => {},
    AddOrUpdateGroupEvent: (evt: AddOrUpdateGroupEvent) => {},
    SearchForGroupsWithNoSuchRoleEvent: (evt: SearchForGroupsWithNoSuchRoleEvent) => {},
    SearchForGroupByNameEvent: (evt: SearchForGroupByNameEvent) => {},
    GetGroupsWithRoleEvent: (evt: GetGroupsWithRoleEvent) => {},
    GetGroupByNameEvent: (evt: GetGroupByNameEvent) => {},
    GetGroupByIdEvent: (evt: GetGroupByIdEvent) => {},
    GetAllGroupsEvent: (evt: GetAllGroupsEvent) => {},
    UpdateItemsStatusEvent: (evt: UpdateItemsStatusEvent) => {},
    UpdateItemValueEvent: (evt: UpdateItemValueEvent) => {},
    UpdateItemEvent: (evt: UpdateItemEvent) => {},
    AddItemEvent: (evt: AddItemEvent) => {},
    AddOrUpdateItemEvent: (evt: AddOrUpdateItemEvent) => {},
    SearchForFavouriteItemsInViewEvent: (evt: SearchForFavouriteItemsInViewEvent) => {},
    SearchForItemsInViewEvent: (evt: SearchForItemsInViewEvent) => {},
    AddFavouriteItemIdsEvent: (evt: AddFavouriteItemIdsEvent) => {},
    RemoveFavouriteItemIdsEvent: (evt: RemoveFavouriteItemIdsEvent) => {},
    GetAllFavouriteItemIdsInViewEvent: (evt: GetAllFavouriteItemIdsInViewEvent) => {},
    GetAllFavouritedItemsInViewEvent: (evt: GetAllFavouritedItemsInViewEvent) => {},
    GetAllItemsInViewEvent: (evt: GetAllItemsInViewEvent) => {},
    GetItemsByIdsEvent: (evt: GetItemsByIdsEvent) => {},
    GetItemByIdEvent: (evt: GetItemByIdEvent) => {},
    GetItemByNameEvent: (evt: GetItemByNameEvent) => {},
    GetItemWithFilteringEvent: (evt: GetItemWithFilteringEvent) => {},
    MarkItemImageAsPrimaryEvent: (evt: MarkItemImageAsPrimaryEvent) => {},
    GetItemPrimaryImageEvent: (evt: GetItemPrimaryImageEvent) => {},
    GetItemImageContentEvent: (evt: GetItemImageContentEvent) => {},
    AddItemImageEvent: (evt: AddItemImageEvent) => {},
    DeleteItemImageEvent: (evt: DeleteItemImageEvent) => {},
    GetJobDetailsByIdEvent: (evt: GetJobDetailsByIdEvent) => {},
    GetAllJobsEvent: (evt: GetAllJobsEvent) => {},
    GetJobByIdEvent: (evt: GetJobByIdEvent) => {},
    CreateJwtTokenEvent: (evt: CreateJwtTokenEvent) => {},
    DecodeJwtTokenEvent: (evt: DecodeJwtTokenEvent) => {},
    VerifyJwtTokenEvent: (evt: VerifyJwtTokenEvent) => {},
    AddUserNotificationEvent: (evt: AddUserNotificationEvent) => {},
    GetUserNotificationsEvent: (evt: GetUserNotificationsEvent) => {},
    GetPricedItemsEvent: (evt: GetPricedItemsEvent) => {},
    GetPricedItemsWithFilteringEvent: (evt: GetPricedItemsWithFilteringEvent) => {},
    SearchGroupsAssociatedWithPricingStructureEvent: (evt: SearchGroupsNotAssociatedWithPricingStructureEvent) => {},
    SearchGroupsNotAssociatedWithPricingStructureEvent: (evt: SearchGroupsNotAssociatedWithPricingStructureEvent) => {},
    GetPricingStructureGroupAssociationsEvent: (evt: GetPricingStructureGroupAssociationsEvent) => {},
    LinkPricingStructureWithGroupIdEvent: (evt: LinkPricingStructureWithGroupIdEvent) => {},
    UnlinkPricingStructureWithGroupIdEvent: (evt: UnlinkPricingStructureWithGroupIdEvent) => {},
    UpdatePricingStructureStatusEvent: (evt: UpdatePricingStructureStatusEvent) => {},
    AddOrUpdatePricingStructuresEvent: (evt: AddOrUpdatePricingStructuresEvent) => {},
    GetPricingStructuresByViewEvent: (evt: GetPricingStructuresByViewEvent) => {},
    GetPartnerPricingStructuresEvent: (evt: GetPartnerPricingStructuresEvent) => {},
    GetAllPricingStructureItemsWithPriceEvent: (evt: GetAllPricingStructureItemsWithPriceEvent) => {},
    GetAllPricingStructuresEvent: (evt: GetAllPricingStructuresEvent) => {},
    GetPricingStructureByNameEvent: (evt: GetPricingStructureByNameEvent) => {},
    GetPricingStructureByIdEvent: (evt: GetPricingStructureByIdEvent) => {},
    SetPricesEvent: (evt: SetPricesEvent) => {},
    AddItemToPricingStructureEvent: (evt: AddItemToPricingStructureEvent) => {},
    GetPricingStructureItemEvent: (evt: GetPricingStructureItemEvent) => {},
    AddOrUpdateRoleEvent: (evt: AddOrUpdateRoleEvent) => {},
    AddRoleToGroupEvent: (evt: AddRoleToGroupEvent) => {},
    GetRoleByNameEvent: (evt: GetRoleByNameEvent) => {},
    GetAllRolesEvent: (evt: GetAllRolesEvent) => {},
    RemoveRoleFromGroup: (evt: RemoveRoleFromGroup) => {},
    AddOrUpdateRuleEvent: (evt: AddOrUpdateRuleEvent) => {},
    UpdateRuleStatusEvent: (evt: UpdateRuleStatusEvent) => {},
    GetRulesEvent: (evt: GetRulesEvent) => {},
    GetRuleEvent: (evt: GetRuleEvent) => {},
    SelfRegisterEvent: (evt: SelfRegisterEvent) => {},
    ApproveSelfRegistrationEvent: (evt: ApproveSelfRegistrationEvent) => {},
    GetAllSelfRegistrationsEvent: (evt: GetAllSelfRegistrationsEvent) => {},
    SearchSelfRegistrationByUsernameEvent: (evt: SearchSelfRegistrationByUsernameEvent) => {},
    DeleteSelfRegistrationEvent: (evt: DeleteSelfRegistrationEvent) => {},
    AddUserEvent: (evt: AddUserEvent) => {},
    UpdateUserEvent: (evt: UpdateUserEvent) => {},
    ChangeUserStatusEvent: (evt: ChangeUserStatusEvent) => {},
    AddUserToGroupEvent: (evt: AddUserToGroupEvent) => {},
    GetUsersInGroupEvent: (evt: GetUsersInGroupEvent) => {},
    GetUsersByStatusEvent: (evt: GetUsersByStatusEvent) => {},
    GetNoAvatarContentEvent: (evt: GetNoAvatarContentEvent) => {},
    GetUserAvatarContentEvent: (evt: GetUserAvatarContentEvent) => {},
    SearchForUserNotInGroupEvent: (evt: SearchForUserNotInGroupEvent) => {},
    SearchUserByUsernameAndStatusEvent: (evt: SearchUserByUsernameAndStatusEvent) => {},
    DeleteUserFromGroupEvent: (evt: DeleteUserFromGroupEvent) => {},
    DeleteUserEvent: (evt: DeleteUserEvent) => {},
    HasAllUserRolesEvent: (evt: HasAllUserRolesEvent) => {},
    HasAnyUserRolesEvent: (evt: HasAnyUserRolesEvent) => {},
    HasNoneUserRolesEvent: (evt: HasNoneUserRolesEvent) => {},
    GetUserByUsernameEvent: (evt: GetUserByUsernameEvent) => {},
    GetUserByIdEvent: (evt: GetUserByIdEvent) => {},
    UpdateUserSettingsEvent: (evt: UpdateUserSettingsEvent) => {},
    GetSettingsEvent: (evt: GetSettingsEvent) => {},
    DeleteViewEvent: (evt: DeleteViewEvent) => {},
    AddOrUpdateViewsEvent: (evt: AddOrUpdateRuleEvent) => {},
    GetAllViewsEvent: (evt: GetAllViewsEvent) => {},
    GetViewByIdEvent: (evt: GetViewByIdEvent) => {},
    GetViewByNameEvent: (evt: GetViewByNameEvent) => {},
    GetViewValidationResultEvent: (evt: GetViewValidationResultEvent) => {},
    GetAllViewValidationsEvent: (evt: GetAllViewValidationsEvent) => {},
    DeleteValidationResultEvent: (evt: DeleteValidationResultEvent) => {},
    GetValidationsByViewIdEvent: (evt: GetValidationsByViewIdEvent) => {},
    GetValidationByViewIdAndValidationIdEvent: (evt: GetValidationByViewIdAndValidationIdEvent) => {}
};

const s: EventSubscriptionRegistry = newEventSubscriptionRegistry(d, `reporting-view-validation-range-summary-subscription`,
    (v1AppRouter: Router, registry: Registry): Promise<void> => {
        // perform db and router related setup
        return null;
    }
);

export default s;

