import * as util from "../util/util";
import {LoginPage} from "../page-object/login.page";
import {ViewRulePage} from "../page-object/sub-page-object/view-rule.page";

describe('view-rule-predefined-base', () => {

    let viewRulePage: ViewRulePage;

    before(() => {
        // const username = Cypress.env('username');
        // const password = Cypress.env('password');
        // viewRulePage = new LoginPage()
        //     .visit()
        //     .login(username, password)
        //     .visitViewPage()
        //     .visitViewRule();
    });

    after(() => {
        // localStorage.clear();
        // sessionStorage.clear();
    });


    beforeEach(() => {
        // cy.restoreLocalStorage();
        const username = Cypress.env('username');
        const password = Cypress.env('password');
        viewRulePage = new LoginPage()
            .visit()
            .login(username, password)
            .visitViewPage()
            .visitViewRule();
    });

    afterEach(() => {
        // cy.saveLocalStorage();
    });

    it('should load', () => {
        viewRulePage
            .visit()
            .validateTitle();
    });

    it('should toggle side nav', () => {
        util.toggleSideNav(() => {
            util.validateSideNavStateOpen(false);
        });
        util.toggleSideNav(() => {
            util.validateSideNavStateOpen(true);
        })
    });

    it('should toggle help nav', () => {
        util.toggleHelpSideNav(() => {
            util.validateHelpNavStateOpen(true);
        });
        util.toggleHelpSideNav(() => {
            util.validateHelpNavStateOpen(false);
        });
    });

    it('should toggle sub side nav', () => {
        util.toggleSubSideNav(() => {
            util.validateSubSideNavStateOpen(false);
        });
        util.toggleSubSideNav(() => {
            util.validateSubSideNavStateOpen(true);
        });
    });

    it('should switch tabs', () => {
        viewRulePage
            .selectCustomTab()
            .verifyCustomTabSelected();

        viewRulePage
            .selectPredefinedTab()
            .verifyPredefinedTabSelected();
    });

    it('should toggle rule expansion panel', () => {
        viewRulePage
            .selectPredefinedTab()
            .togglePanel('Rule #1')
            .verifyPanelExpanded('Rule #1', true)
            .togglePanel('Rule #1')
            .verifyPanelExpanded('Rule #1', false)
            .togglePanel('Rule #2')
            .verifyPanelExpanded('Rule #2', true)
            .togglePanel('Rule #2')
            .verifyPanelExpanded('Rule #2', false)
            .togglePanel('Rule #3')
            .verifyPanelExpanded('Rule #3', true)
            .togglePanel('Rule #3')
            .verifyPanelExpanded('Rule #3', false)
            .togglePanel('Rule #4')
            .verifyPanelExpanded('Rule #4', true)
            .togglePanel('Rule #4')
            .verifyPanelExpanded('Rule #4', false)
            .togglePanel('Rule #5')
            .verifyPanelExpanded('Rule #5', true)
            .togglePanel('Rule #5')
            .verifyPanelExpanded('Rule #5', false)
            .togglePanel('Rule #6')
            .verifyPanelExpanded('Rule #6', true)
            .togglePanel('Rule #6')
            .verifyPanelExpanded('Rule #6', false)
        ;
    });

    it('should be able to enable and disable rules', () => {
        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #1')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #1')
            .enableRule('Rule #1')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #1')
        ;

        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #2')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #2')
            .enableRule('Rule #2')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #2')
        ;


        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #3')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #3')
            .enableRule('Rule #3')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #3')
        ;


        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #4')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #4')
            .enableRule('Rule #4')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #4')
        ;

        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #5')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #5')
            .enableRule('Rule #5')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #5')
        ;

        viewRulePage
            .selectPredefinedTab()
            .disableRule('Rule #6')
            .verifySuccessMessageExists()
            .verifyPanelRuleDisabled('Rule #6')
            .enableRule('Rule #6')
            .verifySuccessMessageExists()
            .verifyPanelRuleEnabled('Rule #6')
        ;
    });

    it('should be able to add / remove validate clauses', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()
            .verifyValidateClauseCount(1)
            .clickAddValidateClause()
            .verifyValidateClauseCount(2)
            .clickAddValidateClause()
            .verifyValidateClauseCount(3)
            .removeValidateClause(1)
            .verifyValidateClauseCount(2)
            .removeValidateClause(1)
            .verifyValidateClauseCount(1)
            .selectValidateClauseAttribute(0, 'string attribute')
            .selectValidateClauseOperator(0, 'eq')
            .clickAddValidateClauseCondition(0)
            .verifyValidateClauseConditionCount(0, 2)
            .clickAddValidateClauseCondition(0)
            .verifyValidateClauseConditionCount(0, 3)
            .clickRemoveValidateClauseCondition(0, 1)
            .verifyValidateClauseConditionCount(0, 2)
            .clickRemoveValidateClauseCondition(0, 1)
            .verifyValidateClauseConditionCount(0, 1)
        ;
    });

    it('should be able to add / remove when clauses', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()
            .verifyWhenClauseCount(1)
            .clickAddWhenClause()
            .verifyWhenClauseCount(2)
            .clickAddWhenClause()
            .verifyWhenClauseCount(3)
            .removeWhenClause(2)
            .verifyWhenClauseCount(2)
            .removeWhenClause(1)
            .verifyWhenClauseCount(1)
            .selectWhenClauseAttribute(0, 'string attribute')
            .selectWhenClauseOperator(0, 'eq')
            .clickAddWhenClauseCondition(0)
            .verifyWhenClauseConditionCount(0, 2)
            .clickAddWhenClauseCondition(0)
            .verifyWhenClauseConditionCount(0, 3)
            .clickRemoveWhenClauseCondition(0, 1)
            .verifyWhenClauseConditionCount(0, 2)
            .clickRemoveWhenClauseCondition(0, 1)
            .verifyWhenClauseConditionCount(0, 1)
        ;
    });

    it ('should be able to string attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'string attribute')
            .verifyWhenClauseAttributeSelected(0, 'string attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'string attribute')
            .verifyValidateClauseAttributeSelected(0, 'string attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });


    it ('should be able to text attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'text attribute')
            .verifyWhenClauseAttributeSelected(0, 'text attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'text attribute')
            .verifyValidateClauseAttributeSelected(0, 'text attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it ('should be able to select attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'select attribute')
            .verifyWhenClauseAttributeSelected(0, 'select attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'select attribute')
            .verifyValidateClauseAttributeSelected(0, 'select attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it ('should be able to double select attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'doubleselect attribute')
            .verifyWhenClauseAttributeSelected(0, 'doubleselect attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'doubleselect attribute')
            .verifyValidateClauseAttributeSelected(0, 'doubleselect attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it ('should be able to number attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'number attribute')
            .verifyWhenClauseAttributeSelected(0, 'number attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'number attribute')
            .verifyValidateClauseAttributeSelected(0, 'number attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it ('should be able to date attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'date attribute')
            .verifyWhenClauseAttributeSelected(0, 'date attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'date attribute')
            .verifyValidateClauseAttributeSelected(0, 'date attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it ('should be able to currency attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'currency attribute')
            .verifyWhenClauseAttributeSelected(0, 'currency attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'currency attribute')
            .verifyValidateClauseAttributeSelected(0, 'currency attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it('should be able to volume attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'volume attribute')
            .verifyWhenClauseAttributeSelected(0, 'volume attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'volume attribute')
            .verifyValidateClauseAttributeSelected(0, 'volume attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it('should be able to area attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'area attribute')
            .verifyWhenClauseAttributeSelected(0, 'area attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'area attribute')
            .verifyValidateClauseAttributeSelected(0, 'area attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it('should be able to width attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'width attribute')
            .verifyWhenClauseAttributeSelected(0, 'width attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'width attribute')
            .verifyValidateClauseAttributeSelected(0, 'width attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it('should be able to height attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'height attribute')
            .verifyWhenClauseAttributeSelected(0, 'height attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'height attribute')
            .verifyValidateClauseAttributeSelected(0, 'height attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });

    it('should be able to length attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'length attribute')
            .verifyWhenClauseAttributeSelected(0, 'length attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)

            // validate clause
            .selectValidateClauseAttribute(0, 'length attribute')
            .verifyValidateClauseAttributeSelected(0, 'length attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
        ;
    });


    it('should be able to dimension attribute in when and validate clause', () => {
        viewRulePage
            .selectPredefinedTab()
            .clickAddRule()

            // when clause
            .selectWhenClauseAttribute(0, 'dimension attribute')
            .verifyWhenClauseAttributeSelected(0, 'dimension attribute')
            .selectWhenClauseOperator(0, 'eq')
            .verifyWhenClauseOperatorSelected(0, 'eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'not eq')
            .verifyWhenClauseOperatorSelected(0, 'not eq')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'empty')
            .verifyWhenClauseOperatorSelected(0, 'empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'not empty')
            .verifyWhenClauseOperatorSelected(0, 'not empty')
            .verifyWhenClauseField1Exists(0, false)
            .verifyWhenClauseField2Exists(0, false)
            .verifyWhenClauseField3Exists(0, false)
            .verifyWhenClauseField4Exists(0, false)
            .selectWhenClauseOperator(0, 'lt')
            .verifyWhenClauseOperatorSelected(0, 'lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'not lt')
            .verifyWhenClauseOperatorSelected(0, 'not lt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'gt')
            .verifyWhenClauseOperatorSelected(0, 'gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'not gt')
            .verifyWhenClauseOperatorSelected(0, 'not gt')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'lte')
            .verifyWhenClauseOperatorSelected(0, 'lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'not lte')
            .verifyWhenClauseOperatorSelected(0, 'not lte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'gte')
            .verifyWhenClauseOperatorSelected(0, 'gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)
            .selectWhenClauseOperator(0, 'not gte')
            .verifyWhenClauseOperatorSelected(0, 'not gte')
            .verifyWhenClauseField1Exists(0, true)
            .verifyWhenClauseField2Exists(0, true)
            .verifyWhenClauseField3Exists(0, true)
            .verifyWhenClauseField4Exists(0, true)

            // validate clause
            .selectValidateClauseAttribute(0, 'dimension attribute')
            .verifyValidateClauseAttributeSelected(0, 'dimension attribute')
            .selectValidateClauseOperator(0, 'eq')
            .verifyValidateClauseOperatorSelected(0, 'eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'not eq')
            .verifyValidateClauseOperatorSelected(0, 'not eq')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'empty')
            .verifyValidateClauseOperatorSelected(0, 'empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'not empty')
            .verifyValidateClauseOperatorSelected(0, 'not empty')
            .verifyValidateClauseField1Exists(0, false)
            .verifyValidateClauseField2Exists(0, false)
            .verifyValidateClauseField3Exists(0, false)
            .verifyValidateClauseField4Exists(0, false)
            .selectValidateClauseOperator(0, 'lt')
            .verifyValidateClauseOperatorSelected(0, 'lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'not lt')
            .verifyValidateClauseOperatorSelected(0, 'not lt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'gt')
            .verifyValidateClauseOperatorSelected(0, 'gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'not gt')
            .verifyValidateClauseOperatorSelected(0, 'not gt')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'lte')
            .verifyValidateClauseOperatorSelected(0, 'lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'not lte')
            .verifyValidateClauseOperatorSelected(0, 'not lte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'gte')
            .verifyValidateClauseOperatorSelected(0, 'gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
            .selectValidateClauseOperator(0, 'not gte')
            .verifyValidateClauseOperatorSelected(0, 'not gte')
            .verifyValidateClauseField1Exists(0, true)
            .verifyValidateClauseField2Exists(0, true)
            .verifyValidateClauseField3Exists(0, true)
            .verifyValidateClauseField4Exists(0, true)
        ;
    });
});
