name: build
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name to Build'
        required: true
        default: 'master'
jobs:
  do-fe-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: fe
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm install
          npm run build       
  do-be-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: be
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm install
          npm run build
  do-wf-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: wf
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: |
          npm install
          npm run build
  
