#
# Build each component of fuyuko, a good sanity test to run to make sure build runs without errors
#   - common
#   - be
#   - fe
#

name: build
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name to Build'
        required: true
        default: 'master'
jobs:
  do-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: check permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          listfile: .github/workflows/super-users
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: build common-code
        working-directory: ./common-code
        run: |
          npm install     
      - name: build be
        working-directory: ./be
        run: |
          npm install
          npm run build
          chmod u+x ./update-files-with-git-hash.sh
          chmod u+x ./update-files-with-git-tag.sh
          ./update-files-with-git-hash.sh
          ./update-files-with-git-tag.sh
      - name: build fe
        working-directory: ./fe
        run: |
          npm install
          npm run build
          chmod u+x ./update-files-with-git-hash.sh
          chmod u+x ./update-files-with-git-tag.sh
          ./update-files-with-git-hash.sh
          ./update-files-with-git-tag.sh
      - name: build wf
        working-directory: ./wf
        run: |
          npm install
          npm run build
