name: docker
on:
  workflow_dispatch:
    inputs:
      branchOrTagName:
        description: 'Branch or Tag Name'
        required: true
        default: 'master'
      dockerVersion:
        description: 'Docker version'
        required: true
        default: 'latest'
jobs:
  do-build:
    runs-on: ubuntu-20.04
    environment: 'docker-hub'
    defaults:
      run: 
        working-directory: .
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchOrTagName}}'
      - name: check permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          listfile: .github/workflows/super-users
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: build source
        run: |
          chmod +x ./build-source.sh;
          ./build-source.sh
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: docker build & publish BE
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tmjee/${{github.event.inputs.dockerVersion}}
          file: ./be/docker/dockerfile
      - name: docker build & publish FE
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tmjee/${{github.event.inputs.dockerVersion}}
          file: ./fe/docker/dockerfile
