#
# Connect to digital ocean kubernetes cluster and run command (this is a template so we can run
#  more kubectl commands on it)
#

name: doctl-demo
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name to Build'
        required: true
        default: 'master'
jobs:
  doctl-access:
    runs-on: ubuntu-20.04
    environment: digitalocean-demo
    env:
      DO_TOKEN: ${{secrets.DO_TOKEN}}
      DO_CLUSTER_NAME: demo-cluster
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: check permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          listfile: .github/workflows/super-users
      - name: doctl setup
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{env.DO_TOKEN}}
      - name: kubernetes tools setup
        uses: stefanprodan/kube-tools@v1.5.0
      - name: doctl kubectl setup
        run: |
          doctl kubernetes cluster kubeconfig save "$DO_CLUSTER_NAME"
      - name: bash command
        run: |
          kubectl get pods && 
          kubectl get deployment
            
