name: doctl-demo
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name to Build'
        required: true
        default: 'master'
jobs:
  doctl-access:
    runs-on: ubuntu-20.04
    environment: digitalocean-demo
    env:
      DO_TOKEN: ${{secrets.DO_TOKEN_R}} 
      DO_CLUSTER_NAME: demo-cluster
    defaults:
      run:
        working-directory: .
    steps:
      #- name: checkout code
      #  uses: actions/checkout@v2
      #  with:
      #    ref: '${{github.event.inputs.branchName}}'
      #- name: setup node
      #  uses: actions/setup-node@v1
      #  with:
      #    node-version: '12.x'
      - name: doctl setup
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{env.DO_TOKEN}}
      - name: kubernetes tools setup
        uses: stefanprodan/kube-tools@v1.5.0
      - name: doctl kubectl setup
        run: |
          doctl kubernetes cluster kubeconfig save "$DO_CLUSTER_NAME"
      - name: bash command
        run: |
          kubectl get pods && 
          kubectl get deployment
            
