#
#  Work In Progress
#
name: k8s-deploy-do-demo-fe
on:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'Branch Name to Build'
        required: true
        default: 'master'
      dockerImageName:
        description: 'fe docker image name'
        required: true
        default: 'tmjee/fuyuko-fe'
      dockerImageVersion:
        description: 'fe docker version tag'
        required: true
        default: 'latest'
jobs:
  deploy-to-docker:
    runs-on: ubuntu-20.04
    environment: digitalocean-demo
    env:
      DOCKER_ACCESS_TOKEN: ${{secrets.DOCKER_ACCESS_TOKEN}}
      DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    defaults:
      run:
        working-directory: .
    steps:
      - name: apt install jq
        run: |
          sudo apt-get install -y jq
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.branchName}}'
      - name: check permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          listfile: .github/workflows/super-users
      - name: doctl setup
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{secrets.DO_TOKEN}}
      - name: kubernetes tools setup
        uses: stefanprodan/kube-tools@v1.5.0
      - name: doctl kubectl setup
        run: |
          doctl kubernetes cluster kubeconfig save "${{secrets.DO_CLUSTER_NAME}}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Git TAG
        run: |
          git describe --tag
      - name: Build source
        run: |
          chmod +x ./build-source.sh;
          ./build-source.sh
      - name: Build and push FE
        uses: docker/build-push-action@v2
        with:
          file: ./fe/docker/dockerfile
          context: ./fe
          push: true
          tags: ${{github.event.inputs.dockerImageName}}:${{github.event.inputs.dockerImageVersion}}
      - name: update config file
        run: |
          jq '.api_host_url="${{secrets.BE_URL}}"' < ./fe/dist/fuyuko/assets/config.json > config.json;
          kubectl create configmap fuyuko-fe-config --from-file ./config.json -o yaml --dry-run | kubectl replace -f -
      - name: bash command
        run: |
          kubectl apply -f ./kubernetes/k8s-fuyuko-fe-deployment.yaml &&
          sleep 10 &&
          kubectl scale --replicas=0 -f ./kubernetes/k8s-fuyuko-fe-deployment.yaml &&
          sleep 10 &&
          kubectl apply -f ./kubernetes/k8s-fuyuko-fe-deployment.yaml &&
          sleep 10 &&
          kubectl get pods &&
          kubectl get deployment
