name: release
on:
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag to release'
        required: true
        default: 'v-testing-tag'
      draft:
        description: 'Draft release?'
        required: true
        default: 'false'
      prerelease:
        description: 'Prerelease?'
        required: true
        default: 'true'

jobs:
  do-build:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: '${{github.event.inputs.tagName}}'
      - name: debug
        run: |
          echo "$GITHUB_REF";
          echo "$GITHUB_HEAD_REF";
          echo "$GITHUB_BASE_REF";
          echo "${{github.event.inputs.tagName}}";
      #- name: check if tag is valid
      #  if: ${{!(startsWith(github.ref, 'refs/tags/'))}}
      #  run: |
      #    echo "A tag needs to be given"; exit 1;
      - name: check permission
        uses: 74th/workflow-permission-action@1.0.0
        with:
          listfile: .github/workflows/super-users
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'    
      - name: update fe files with git hash
        working-directory: ./fe
        run: |
          ./update-files-with-git-hash.sh
      - name: update be files with git hash
        working-directory: ./be
        run: |
          ./update-files-with-git-hash.sh
      - name: build common-code
        working-directory: ./common-code
        run: |
          npm install     
      - name: build be
        working-directory: ./be
        run: |
          npm install
          npm run build
      - name: build fe
        working-directory: ./fe
        run: |
          npm install
          npm run build    
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: '${{github.event.inputs.draft}}'
          prerelease: '${{github.event.inputs.prerelease}}'
          tag_name: '${{github.event.inputs.tagName}}'
